<funkload version="1.16.1" time="2018-06-13T09:43:32.816561">
<config key="sleep_time_min" value="0.0" />
<config key="node" value="Zorro-HP-Z620" />
<config key="startup_delay" value="0.2" />
<config key="cycles" value="[1, 10, 20]" />
<config key="cycle_time" value="1.0" />
<config key="description" value="XXX the test case description" />
<config key="configuration_file" value="/home/nlarsson/bbk/python/webdev/museumflask/funktests/BasicNavigation.conf" />
<config key="class_title" value="BasicNavigation" />
<config key="server_url" value="http://193.61.44.11:3033" />
<config key="module" value="test_BasicNavigation" />
<config key="id" value="test_basic_navigation" />
<config key="class_description" value="XXX the TestCase class description" />
<config key="sleep_time" value="1.0" />
<config key="sleep_time_max" value="2.0" />
<config key="duration" value="30" />
<config key="method" value="test_basic_navigation" />
<config key="log_xml" value="/home/nlarsson/bbk/python/webdev/museumflask/funktests/basic_navigation-bench.xml" />
<config key="class" value="BasicNavigation" />
<config key="python_version" value="2.7.12" />
<response cycle="000" cvus="001" thread="000" suite="BasicNavigation" name="test_basic_navigation" step="001" number="001" type="get" result="Error" url="http://193.61.44.11:3033/visualisations" code="-1" description="Get /visualisations" time="1528879413.82" duration="0.000444173812866" traceback='Traceback (most recent call last):&#10;   File "/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py", line 202, in _connect&#10;    cert_file=self._certfile_path, method=rtype)&#10;   File "/usr/lib/python2.7/dist-packages/funkload/PatchWebunit.py", line 360, in WF_fetch&#10;    h.endheaders()&#10;   File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders&#10;    self._send_output(message_body)&#10;   File "/usr/lib/python2.7/httplib.py", line 897, in _send_output&#10;    self.send(msg)&#10;   File "/usr/lib/python2.7/httplib.py", line 859, in send&#10;    self.connect()&#10;   File "/usr/lib/python2.7/httplib.py", line 836, in connect&#10;    self.timeout, self.source_address)&#10;   File "/usr/lib/python2.7/socket.py", line 575, in create_connection&#10;    raise err&#10; error: [Errno 111] Connection refused&#10;' />
<testResult cycle="000" cvus="001" thread="000" suite="BasicNavigation" name="test_basic_navigation"  time="1528879413.82" result="Error" steps="1" duration="0.00136613845825" connection_duration="0.000444173812866" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/home/nlarsson/bbk/python/webdev/museumflask/funktests/test_BasicNavigation.py&quot;, line 37, in test_basic_navigation&#10;    description=&quot;Get /visualisations&quot;)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 221, in _connect&#10;    raise SocketError(&quot;Can't load %s.&quot; % url)&#10; error: Can't load http://193.61.44.11:3033/visualisations.&#10;" />
<response cycle="000" cvus="001" thread="000" suite="BasicNavigation" name="test_basic_navigation" step="001" number="001" type="get" result="Error" url="http://193.61.44.11:3033/visualisations" code="-1" description="Get /visualisations" time="1528879414.82" duration="0.00014591217041" traceback='Traceback (most recent call last):&#10;   File "/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py", line 202, in _connect&#10;    cert_file=self._certfile_path, method=rtype)&#10;   File "/usr/lib/python2.7/dist-packages/funkload/PatchWebunit.py", line 360, in WF_fetch&#10;    h.endheaders()&#10;   File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders&#10;    self._send_output(message_body)&#10;   File "/usr/lib/python2.7/httplib.py", line 897, in _send_output&#10;    self.send(msg)&#10;   File "/usr/lib/python2.7/httplib.py", line 859, in send&#10;    self.connect()&#10;   File "/usr/lib/python2.7/httplib.py", line 836, in connect&#10;    self.timeout, self.source_address)&#10;   File "/usr/lib/python2.7/socket.py", line 575, in create_connection&#10;    raise err&#10; error: [Errno 111] Connection refused&#10;' />
<testResult cycle="000" cvus="001" thread="000" suite="BasicNavigation" name="test_basic_navigation"  time="1528879414.82" result="Error" steps="1" duration="0.000442028045654" connection_duration="0.00014591217041" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/home/nlarsson/bbk/python/webdev/museumflask/funktests/test_BasicNavigation.py&quot;, line 37, in test_basic_navigation&#10;    description=&quot;Get /visualisations&quot;)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 221, in _connect&#10;    raise SocketError(&quot;Can't load %s.&quot; % url)&#10; error: Can't load http://193.61.44.11:3033/visualisations.&#10;" />
<response cycle="000" cvus="001" thread="000" suite="BasicNavigation" name="test_basic_navigation" step="001" number="001" type="get" result="Error" url="http://193.61.44.11:3033/visualisations" code="-1" description="Get /visualisations" time="1528879415.83" duration="0.00042200088501" traceback='Traceback (most recent call last):&#10;   File "/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py", line 202, in _connect&#10;    cert_file=self._certfile_path, method=rtype)&#10;   File "/usr/lib/python2.7/dist-packages/funkload/PatchWebunit.py", line 360, in WF_fetch&#10;    h.endheaders()&#10;   File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders&#10;    self._send_output(message_body)&#10;   File "/usr/lib/python2.7/httplib.py", line 897, in _send_output&#10;    self.send(msg)&#10;   File "/usr/lib/python2.7/httplib.py", line 859, in send&#10;    self.connect()&#10;   File "/usr/lib/python2.7/httplib.py", line 836, in connect&#10;    self.timeout, self.source_address)&#10;   File "/usr/lib/python2.7/socket.py", line 575, in create_connection&#10;    raise err&#10; error: [Errno 111] Connection refused&#10;' />
<testResult cycle="000" cvus="001" thread="000" suite="BasicNavigation" name="test_basic_navigation"  time="1528879415.83" result="Error" steps="1" duration="0.00133490562439" connection_duration="0.00042200088501" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/home/nlarsson/bbk/python/webdev/museumflask/funktests/test_BasicNavigation.py&quot;, line 37, in test_basic_navigation&#10;    description=&quot;Get /visualisations&quot;)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 221, in _connect&#10;    raise SocketError(&quot;Can't load %s.&quot; % url)&#10; error: Can't load http://193.61.44.11:3033/visualisations.&#10;" />
<response cycle="000" cvus="001" thread="000" suite="BasicNavigation" name="test_basic_navigation" step="001" number="001" type="get" result="Error" url="http://193.61.44.11:3033/visualisations" code="-1" description="Get /visualisations" time="1528879416.83" duration="0.00017786026001" traceback='Traceback (most recent call last):&#10;   File "/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py", line 202, in _connect&#10;    cert_file=self._certfile_path, method=rtype)&#10;   File "/usr/lib/python2.7/dist-packages/funkload/PatchWebunit.py", line 360, in WF_fetch&#10;    h.endheaders()&#10;   File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders&#10;    self._send_output(message_body)&#10;   File "/usr/lib/python2.7/httplib.py", line 897, in _send_output&#10;    self.send(msg)&#10;   File "/usr/lib/python2.7/httplib.py", line 859, in send&#10;    self.connect()&#10;   File "/usr/lib/python2.7/httplib.py", line 836, in connect&#10;    self.timeout, self.source_address)&#10;   File "/usr/lib/python2.7/socket.py", line 575, in create_connection&#10;    raise err&#10; error: [Errno 111] Connection refused&#10;' />
<testResult cycle="000" cvus="001" thread="000" suite="BasicNavigation" name="test_basic_navigation"  time="1528879416.83" result="Error" steps="1" duration="0.000560998916626" connection_duration="0.00017786026001" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/home/nlarsson/bbk/python/webdev/museumflask/funktests/test_BasicNavigation.py&quot;, line 37, in test_basic_navigation&#10;    description=&quot;Get /visualisations&quot;)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 221, in _connect&#10;    raise SocketError(&quot;Can't load %s.&quot; % url)&#10; error: Can't load http://193.61.44.11:3033/visualisations.&#10;" />
<response cycle="000" cvus="001" thread="000" suite="BasicNavigation" name="test_basic_navigation" step="001" number="001" type="get" result="Error" url="http://193.61.44.11:3033/visualisations" code="-1" description="Get /visualisations" time="1528879417.83" duration="0.000158786773682" traceback='Traceback (most recent call last):&#10;   File "/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py", line 202, in _connect&#10;    cert_file=self._certfile_path, method=rtype)&#10;   File "/usr/lib/python2.7/dist-packages/funkload/PatchWebunit.py", line 360, in WF_fetch&#10;    h.endheaders()&#10;   File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders&#10;    self._send_output(message_body)&#10;   File "/usr/lib/python2.7/httplib.py", line 897, in _send_output&#10;    self.send(msg)&#10;   File "/usr/lib/python2.7/httplib.py", line 859, in send&#10;    self.connect()&#10;   File "/usr/lib/python2.7/httplib.py", line 836, in connect&#10;    self.timeout, self.source_address)&#10;   File "/usr/lib/python2.7/socket.py", line 575, in create_connection&#10;    raise err&#10; error: [Errno 111] Connection refused&#10;' />
<testResult cycle="000" cvus="001" thread="000" suite="BasicNavigation" name="test_basic_navigation"  time="1528879417.83" result="Error" steps="1" duration="0.00068998336792" connection_duration="0.000158786773682" requests="1" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback="Traceback (most recent call last):&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 946, in __call__&#10;    testMethod()&#10;   File &quot;/home/nlarsson/bbk/python/webdev/museumflask/funktests/test_BasicNavigation.py&quot;, line 37, in test_basic_navigation&#10;    description=&quot;Get /visualisations&quot;)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 391, in get&#10;    method=&quot;get&quot;, load_auto_links=load_auto_links)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 299, in _browse&#10;    response = self._connect(url, params, ok_codes, method, description)&#10;   File &quot;/usr/lib/python2.7/dist-packages/funkload/FunkLoadTestCase.py&quot;, line 221, in _connect&#10;    raise SocketError(&quot;Can't load %s.&quot; % url)&#10; error: Can't load http://193.61.44.11:3033/visualisations.&#10;" />
